name: oidc

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    healthcheck:
      test:
        ["CMD", "cloudflared", "tunnel", "--metrics", "0.0.0.0:20241", "ready"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - tunnel

  webfinger:
    build: ./webfinger
    container_name: webfinger
    restart: unless-stopped
    environment:
      - ISSUER_DOMAIN=${TINYAUTH_DOMAIN}
      - DATABASE_URL=${LLDAP_DATABASE_URL}
      - PORT=8000
    networks:
      - tunnel

  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    volumes:
      - lldap-data:/data
    environment:
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=${LLDAP_LDAP_BASE_DN}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_DATABASE_URL=${LLDAP_DATABASE_URL}
    networks:
      - tunnel

  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - TINYAUTH_LDAP_ADDRESS=ldap://lldap:3890
      - TINYAUTH_LDAP_BINDDN=uid=${TINYAUTH_LDAP_OBSERVER_ID},ou=people,${LLDAP_LDAP_BASE_DN}
      - TINYAUTH_LDAP_BINDPASSWORD=${TINYAUTH_LDAP_OBSERVER_PASSWORD}
      - TINYAUTH_LDAP_BASEDN=${LLDAP_LDAP_BASE_DN}
      - TINYAUTH_LDAP_SEARCHFILTER=(uid=%s)
      - TINYAUTH_LDAP_INSECURE=true
      - TINYAUTH_APPURL=${TINYAUTH_DOMAIN}
      - TINYAUTH_OIDC_CLIENTS_TAILSCALE_CLIENTID=${TINYAUTH_OIDC_CLIENTS_TAILSCALE_CLIENTID}
      - TINYAUTH_OIDC_CLIENTS_TAILSCALE_CLIENTSECRET=${TINYAUTH_OIDC_CLIENTS_TAILSCALE_CLIENTSECRET}
      - TINYAUTH_OIDC_CLIENTS_TAILSCALE_NAME=${TINYAUTH_OIDC_CLIENTS_TAILSCALE_NAME}
    volumes:
      - tinyauth-data:/data
    networks:
      - tunnel

networks:
  tunnel:
    driver: bridge

volumes:
  lldap-data:
  tinyauth-data:
